"
I am an application to edit the commit history of a Subversion repository, with an optional conversion to git.

I am responsible for coordinating the actions of the app: Read the dump file, edit it, write the results out to disk.  I know about SVN dump objects and their editors.

I am the senior class representing the app, so I don't have collaborators; instead, I delegate to the objects that compose me.

Public API and Key Messages:  #TODO

- message one   
- message two 
- (for bonus points) how to create instances.

   One simple example is simply gorgeous.
 
Internal Representation and Key Implementation Points.


    Implementation Points
"
Class {
	#name : #SVNEdit,
	#superclass : #Object,
	#category : #'SVN-Edit'
}
